/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Characters
         * @description List all library characters.
         */
        get: operations["list_characters_api_characters_get"];
        put?: never;
        /**
         * Export Character
         * @description Export a character to the library.
         */
        post: operations["export_character_api_characters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Character
         * @description Create a new library character via LLM from a concept description.
         */
        post: operations["create_character_api_characters_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/import-from-story": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import From Story
         * @description Import characters from a saved game into the library.
         */
        post: operations["import_from_story_api_characters_import_from_story_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{library_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Character
         * @description Get a single library character.
         */
        get: operations["get_character_api_characters__library_id__get"];
        /**
         * Update Character
         * @description Edit character fields.
         */
        put: operations["update_character_api_characters__library_id__put"];
        post?: never;
        /**
         * Delete Character
         * @description Remove a character from the library.
         */
        delete: operations["delete_character_api_characters__library_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{library_id}/edit-portrait": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Portrait
         * @description Edit portrait prompt and regenerate.
         */
        post: operations["edit_portrait_api_characters__library_id__edit_portrait_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{library_id}/portrait": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Character Portrait
         * @description Serve a library character's portrait PNG.
         */
        get: operations["get_character_portrait_api_characters__library_id__portrait_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{library_id}/reference-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reference Image
         * @description Serve a library character's reference image PNG.
         */
        get: operations["get_reference_image_api_characters__library_id__reference_image_get"];
        put?: never;
        /**
         * Upload Reference Image
         * @description Upload a reference image for a library character.
         *
         *     Accepts multipart form with ``image`` file and ``mode`` field
         *     (``"use_as_is"`` or ``"style_transfer"``).
         */
        post: operations["upload_reference_image_api_characters__library_id__reference_image_post"];
        /**
         * Delete Reference Image
         * @description Remove a character's reference image.
         */
        delete: operations["delete_reference_image_api_characters__library_id__reference_image_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{library_id}/regenerate-portrait": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Portrait
         * @description Regenerate a library character's portrait using their stored portrait_prompt.
         */
        post: operations["regenerate_portrait_api_characters__library_id__regenerate_portrait_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Games
         * @description List all saved games with summary metadata.
         *
         *     Delegates to :func:`storygen.storage.save.list_game_summaries` so the
         *     schema-extraction logic lives in the storage layer (migration-aware,
         *     single source of truth) rather than hand-parsing JSON in the router.
         */
        get: operations["list_games_api_games_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game
         * @description Return full game state.
         */
        get: operations["get_game_api_games__game_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Game Endpoint
         * @description Delete a game save.
         */
        delete: operations["delete_game_endpoint_api_games__game_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/advance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Advance Game
         * @description Pick a choice and advance the story.
         */
        post: operations["advance_game_api_games__game_id__advance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/endings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Endings
         * @description List reached ending node IDs.
         */
        get: operations["list_endings_api_games__game_id__endings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/export-book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Book Endpoint
         * @description Export the current ending path as an HTML book.
         */
        post: operations["export_book_endpoint_api_games__game_id__export_book_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/export-book/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Book
         * @description Download the exported HTML book as a file.
         */
        get: operations["download_book_api_games__game_id__export_book_download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Graph
         * @description Return all choice edges for the story graph (visited + unvisited).
         */
        get: operations["get_graph_api_games__game_id__graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/jump": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Jump To Node
         * @description Set the current node to a target node.
         */
        post: operations["jump_to_node_api_games__game_id__jump_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Path
         * @description Return the path from root to target node.
         */
        get: operations["get_path_api_games__game_id__path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/prune": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prune Subtree Endpoint
         * @description Prune a subtree starting at the given node.
         */
        post: operations["prune_subtree_endpoint_api_games__game_id__prune_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/games/{game_id}/regenerate-node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Node
         * @description Regenerate the current node by pruning it and re-advending from parent.
         */
        post: operations["regenerate_node_api_games__game_id__regenerate_node_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["_health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{game_id}/cover/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Cover
         * @description Regenerate the cover art (root node scene image).
         */
        post: operations["regenerate_cover_api_images__game_id__cover_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{game_id}/portrait/{char_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Portrait Image
         * @description Serve the latest character portrait PNG.
         */
        get: operations["get_portrait_image_api_images__game_id__portrait__char_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{game_id}/portrait/{char_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Portrait
         * @description Edit a character portrait prompt and regenerate.
         */
        post: operations["edit_portrait_api_images__game_id__portrait__char_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{game_id}/portrait/{char_id}/outfit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Outfit
         * @description Create a new outfit for a character and generate its portrait.
         */
        post: operations["add_outfit_api_images__game_id__portrait__char_id__outfit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{game_id}/portrait/{char_id}/outfit/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revert Outfit
         * @description Revert to the base portrait (unset current outfit).
         */
        post: operations["revert_outfit_api_images__game_id__portrait__char_id__outfit_revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{game_id}/portrait/{char_id}/outfit/{outfit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Outfit
         * @description Delete an outfit.
         */
        delete: operations["delete_outfit_api_images__game_id__portrait__char_id__outfit__outfit_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{game_id}/portrait/{char_id}/outfit/{outfit_id}/set": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Outfit
         * @description Set an outfit as the current active outfit.
         */
        post: operations["set_outfit_api_images__game_id__portrait__char_id__outfit__outfit_id__set_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{game_id}/portrait/{char_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Portrait
         * @description Retry (regenerate) a character portrait using the stored portrait_prompt.
         */
        post: operations["retry_portrait_api_images__game_id__portrait__char_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{game_id}/scene/{node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scene Image
         * @description Serve a scene PNG for a story node.
         */
        get: operations["get_scene_image_api_images__game_id__scene__node_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{game_id}/scene/{node_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Scene
         * @description Edit scene prompt and regenerate.
         */
        post: operations["edit_scene_api_images__game_id__scene__node_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/images/{game_id}/scene/{node_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Scene
         * @description Retry scene image generation for a node.
         */
        post: operations["retry_scene_api_images__game_id__scene__node_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Presets */
        get: operations["list_presets_api_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Settings
         * @description Return the full application state.
         */
        get: operations["get_settings_api_settings_get"];
        /**
         * Update Settings
         * @description Write settings and return the updated state.
         *
         *     SEC-002: provider ``base_url`` values are validated against a curated
         *     allowlist (and private/link-local IP ranges are rejected) before being
         *     persisted, so the next outbound LLM/image request cannot leak the user's
         *     API key to an attacker-controlled host.
         */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tts/{game_id}/{node_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tts Audio
         * @description Serve cached TTS audio for a node.
         */
        get: operations["get_tts_audio_api_tts__game_id___node_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tts/{game_id}/{node_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Tts
         * @description Generate TTS audio for a node's narration and return the audio URL.
         */
        post: operations["generate_tts_api_tts__game_id___node_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tts/{game_id}/{node_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Tts Status
         * @description Check if TTS audio exists for a node.
         */
        get: operations["tts_status_api_tts__game_id___node_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wizard/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wizard Characters
         * @description Generate characters for a theme.
         */
        post: operations["wizard_characters_api_wizard_characters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wizard/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wizard Confirm
         * @description Build the initial save and generate portraits.
         */
        post: operations["wizard_confirm_api_wizard_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wizard/theme": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wizard Theme
         * @description Generate a story theme from a prompt.
         */
        post: operations["wizard_theme_api_wizard_theme_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AdvanceRequest
         * @description Body for `POST /api/games/{id}/advance` — pick a choice.
         */
        AdvanceRequest: {
            /**
             * Choice Id
             * @description Id of the choice being taken.
             */
            choice_id: string;
            /**
             * From Node Id
             * @description Node the choice is being taken from.
             */
            from_node_id: string;
        };
        /**
         * AdvanceResponse
         * @description Result of an advance: the landed node plus any side effects.
         */
        AdvanceResponse: {
            /**
             * Image Status
             * @description Scene-image state at response time (the image may still be rendering asynchronously).
             */
            image_status?: string | null;
            /**
             * New Characters
             * @description Characters introduced by this beat (may be empty).
             */
            new_characters: components["schemas"]["Character"][];
            node: components["schemas"]["NodeDetail"];
        };
        /** Body_upload_reference_image_api_characters__library_id__reference_image_post */
        Body_upload_reference_image_api_characters__library_id__reference_image_post: {
            /** Image */
            image: string;
        };
        /**
         * Character
         * @description A character who appears in the story.
         */
        Character: {
            /** Backstory */
            backstory: string;
            /** Backstory Summary */
            backstory_summary?: string | null;
            /** Current Outfit Id */
            current_outfit_id?: string | null;
            /** Id */
            id: string;
            /** Introduced At Node Id */
            introduced_at_node_id: string;
            /** Name */
            name: string;
            /** Outfits */
            outfits?: components["schemas"]["CharacterOutfit"][];
            /** Personality */
            personality: string;
            /** Physical Description */
            physical_description: string;
            /** Portrait Path */
            portrait_path?: string | null;
            /** Portrait Prompt */
            portrait_prompt?: string | null;
            /** Reference Image Path */
            reference_image_path?: string | null;
        };
        /**
         * CharacterCreateRequest
         * @description Body for creating a new library character from a concept.
         */
        CharacterCreateRequest: {
            /** Concept */
            concept: string;
            /**
             * Name
             * @default
             */
            name: string;
        };
        /**
         * CharacterExportRequest
         * @description Body for exporting a character into the library.
         */
        CharacterExportRequest: {
            /** Backstory */
            backstory: string;
            /** Character Id */
            character_id?: string | null;
            /** Name */
            name: string;
            /** Personality */
            personality: string;
            /** Physical Description */
            physical_description: string;
            /**
             * Portrait Prompt
             * @default
             */
            portrait_prompt: string;
            /**
             * Save Id
             * @default
             */
            save_id: string;
            /**
             * Save Title
             * @default
             */
            save_title: string;
        };
        /**
         * CharacterLibraryEntry
         * @description One exported character in the cross-game library.
         */
        CharacterLibraryEntry: {
            /** Backstory */
            backstory: string;
            /**
             * Exported At
             * Format: date-time
             * @description When the character was exported.
             */
            exported_at: string;
            /**
             * Has Portrait
             * @default false
             */
            has_portrait: boolean;
            /**
             * Has Reference Image
             * @default false
             */
            has_reference_image: boolean;
            /**
             * Id
             * @description Library id (uuid4 hex, independent of save char id).
             */
            id: string;
            /** Name */
            name: string;
            /** Personality */
            personality: string;
            /** Physical Description */
            physical_description: string;
            /**
             * Portrait Prompt
             * @description Prompt the portrait was generated from.
             */
            portrait_prompt: string;
            /** Reference Image Path */
            reference_image_path?: string | null;
            /**
             * Source
             * @default export
             */
            source: string;
        };
        /**
         * CharacterLibraryResponse
         * @description Response envelope for `GET /api/library`.
         */
        CharacterLibraryResponse: {
            /** Characters */
            characters: components["schemas"]["CharacterLibraryEntry"][];
        };
        /**
         * CharacterOutfit
         * @description A named outfit variant for a character — its own portrait + prompt.
         *
         *     Outfits are sidecar references stored on ``Character.outfits``. Setting one
         *     as current copies its ``portrait_path`` / ``portrait_prompt`` into the
         *     character's main fields, so scene-generation code (which reads
         *     ``Character.portrait_path``) picks the active outfit up automatically.
         *
         *     Attributes:
         *         id: Stable identifier (uuid4 hex, 32 lowercase chars).
         *         name: Human-readable label (e.g. ``"casual"``, ``"ballroom gown"``).
         *         description: Prompt addition describing the outfit (e.g. ``"wearing a
         *             red gown with gold trim"``).
         *         portrait_path: Outfit portrait path, relative to the save directory
         *             (mirrors ``Character.portrait_path`` storage convention).
         *         portrait_prompt: Full prompt used to generate the portrait, retained so
         *             the outfit can be regenerated later with identical wording.
         *         created_at: When the outfit was added. Required — caller passes
         *             ``datetime.now(UTC)`` at creation time.
         */
        CharacterOutfit: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Portrait Path */
            portrait_path: string;
            /** Portrait Prompt */
            portrait_prompt: string;
        };
        /**
         * CharacterUpdateRequest
         * @description Partial update for an in-place library character edit.
         */
        CharacterUpdateRequest: {
            /** Backstory */
            backstory?: string | null;
            /** Name */
            name?: string | null;
            /** Personality */
            personality?: string | null;
            /** Physical Description */
            physical_description?: string | null;
            /** Portrait Prompt */
            portrait_prompt?: string | null;
        };
        /**
         * ChoiceOption
         * @description A single choice offered at a node, with its resolved child if explored.
         */
        ChoiceOption: {
            /**
             * Child Node Id
             * @description Id of the node this choice leads to, or null while unexplored.
             */
            child_node_id?: string | null;
            /**
             * Id
             * @description Stable choice id (unique within the parent node).
             */
            id: string;
            /**
             * Text
             * @description Player-facing choice label.
             */
            text: string;
        };
        /**
         * GameDetail
         * @description Full game state: the node tree plus aggregated metadata.
         */
        GameDetail: {
            /**
             * Art Style
             * @description Art-style string threaded into image prompts.
             */
            art_style: string;
            /**
             * Characters
             * @description Current cast roster (may grow mid-story).
             */
            characters: {
                [key: string]: unknown;
            }[];
            /**
             * Created At
             * Format: date-time
             * @description Save creation time.
             */
            created_at: string;
            /**
             * Current Node Id
             * @description Cursor position in the tree.
             */
            current_node_id: string;
            /**
             * Endings Reached
             * @description Node ids of every ending the player has reached.
             */
            endings_reached: string[];
            /**
             * Id
             * @description Save UUID (hex).
             */
            id: string;
            /**
             * Nodes
             * @description Full node map keyed by id.
             */
            nodes: {
                [key: string]: components["schemas"]["NodeDetail"];
            };
            /**
             * Relationships
             * @default []
             */
            relationships: {
                [key: string]: unknown;
            }[];
            /**
             * Root Node Id
             * @description Root node id.
             */
            root_node_id: string;
            /**
             * Text Total Input Tokens
             * @description Cumulative input tokens.
             * @default 0
             */
            text_total_input_tokens: number;
            /**
             * Text Total Output Tokens
             * @description Cumulative output tokens.
             * @default 0
             */
            text_total_output_tokens: number;
            /**
             * Text Total Requests
             * @description Cumulative LLM call count.
             * @default 0
             */
            text_total_requests: number;
            /**
             * Theme
             * @description Theme blob (premise, tone, etc.).
             */
            theme: {
                [key: string]: unknown;
            };
            /**
             * Title
             * @description Human-readable story title.
             */
            title: string;
            /**
             * Tone
             * @description Tone blob (preset + descriptor).
             */
            tone: {
                [key: string]: unknown;
            };
            /**
             * Total Image Cost Usd
             * @description Cumulative image spend in USD.
             * @default 0
             */
            total_image_cost_usd: number;
            /**
             * Updated At
             * Format: date-time
             * @description Last write time.
             */
            updated_at: string;
        };
        /**
         * GameListResponse
         * @description Response envelope for `GET /api/games`.
         */
        GameListResponse: {
            /** Games */
            games: components["schemas"]["GameSummary"][];
        };
        /**
         * GameSummary
         * @description One row in the game list (lightweight, no node tree).
         */
        GameSummary: {
            /**
             * Has Cover
             * @default false
             */
            has_cover: boolean;
            /**
             * Id
             * @description Save UUID (hex).
             */
            id: string;
            /**
             * Is Ending
             * @description True when the current cursor sits on a terminal (ending) node.
             */
            is_ending: boolean;
            /**
             * Node Count
             * @description Number of nodes currently in the tree.
             */
            node_count: number;
            /**
             * Title
             * @description Human-readable story title.
             */
            title: string;
            /**
             * Updated At
             * Format: date-time
             * @description Last write time of the save.
             */
            updated_at: string;
        };
        /**
         * GraphEdge
         * @description One parent→child edge in the story tree.
         */
        GraphEdge: {
            /**
             * Child Id
             * @description Child node id, or null while unexplored.
             */
            child_id?: string | null;
            /**
             * Choice Text
             * @description Label of the choice leading to the child.
             */
            choice_text: string;
            /**
             * Parent Id
             * @description Parent node id.
             */
            parent_id: string;
        };
        /**
         * GraphResponse
         * @description Edge list for `GET /api/games/{id}/graph`.
         */
        GraphResponse: {
            /** Edges */
            edges: components["schemas"]["GraphEdge"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JumpRequest
         * @description Body for the jump-to-node endpoint.
         */
        JumpRequest: {
            /**
             * Target Node Id
             * @description Node to move the cursor to.
             */
            target_node_id: string;
        };
        /**
         * NodeDetail
         * @description Full projection of a single story node for the client.
         */
        NodeDetail: {
            /**
             * Choices
             * @default []
             */
            choices: components["schemas"]["ChoiceOption"][];
            /**
             * Chosen Choice Id
             * @description Id of the choice taken from the parent to reach this node.
             */
            chosen_choice_id?: string | null;
            /**
             * Created At
             * Format: date-time
             * @description When the node was first committed.
             */
            created_at: string;
            /**
             * Id
             * @description Node id (content-addressed).
             */
            id: string;
            /**
             * Image Path
             * @description Relative path to the scene image, when present.
             */
            image_path?: string | null;
            /**
             * Image Prompt
             * @description Prompt used (or to be used) for the scene image.
             */
            image_prompt?: string | null;
            /**
             * Image Status
             * @description Scene-image lifecycle state: not_planned | generating | done | failed.
             */
            image_status?: string | null;
            /**
             * Is Ending
             * @description True when this node ends the story.
             */
            is_ending: boolean;
            /**
             * Is Major
             * @description True for major (summary-triggering) beats.
             */
            is_major: boolean;
            /**
             * Narration
             * @description Narration text shown to the player.
             */
            narration: string;
            /**
             * Parent Id
             * @description Parent node id; null for the root.
             */
            parent_id?: string | null;
            /**
             * Summary To Here
             * @description Cumulative story-so-far summary anchored at this node, present only on major beats.
             */
            summary_to_here?: string | null;
        };
        /**
         * OutfitRequest
         * @description Body for creating a character outfit.
         */
        OutfitRequest: {
            /** Description */
            description: string;
            /** Name */
            name: string;
        };
        /**
         * PortraitEditRequest
         * @description Body for the portrait edit/regenerate endpoint.
         */
        PortraitEditRequest: {
            /**
             * Art Style
             * @default children's story book
             */
            art_style: string;
            /**
             * Mode
             * @default edit
             */
            mode: string;
            /** Prompt */
            prompt: string;
            /**
             * Use Current As Ref
             * @default false
             */
            use_current_as_ref: boolean;
        };
        /**
         * PortraitRegenerateRequest
         * @description Body for the portrait-regenerate endpoint.
         */
        PortraitRegenerateRequest: {
            /**
             * Art Style
             * @default children's story book
             */
            art_style: string;
        };
        /**
         * PruneRequest
         * @description Body for the prune-subtree endpoint.
         */
        PruneRequest: {
            /**
             * Node Id
             * @description Root of the subtree to delete.
             */
            node_id: string;
        };
        /**
         * RegenerateNodeRequest
         * @description Re-roll the current node by pruning it and re-advancing from the parent.
         */
        RegenerateNodeRequest: Record<string, never>;
        /**
         * SceneEditRequest
         * @description Body for the scene-prompt-edit endpoint.
         */
        SceneEditRequest: {
            /** Prompt */
            prompt: string;
        };
        /**
         * SettingsResponse
         * @description Snapshot of every persisted preference + provider default.
         */
        SettingsResponse: {
            /**
             * Art Enabled
             * @default true
             */
            art_enabled: boolean;
            /**
             * Auto Open Art Enabled
             * @default false
             */
            auto_open_art_enabled: boolean;
            /**
             * Auto Recap Enabled
             * @default false
             */
            auto_recap_enabled: boolean;
            /**
             * Auto Select Enabled
             * @default false
             */
            auto_select_enabled: boolean;
            /**
             * Character Image Provider
             * @default {}
             */
            character_image_provider: {
                [key: string]: unknown;
            };
            /**
             * Graphics Mode
             * @default halfblock
             */
            graphics_mode: string;
            /**
             * Image Provider
             * @default {}
             */
            image_provider: {
                [key: string]: unknown;
            };
            /**
             * Image Streaming Enabled
             * @default false
             */
            image_streaming_enabled: boolean;
            /**
             * Llm Cache Enabled
             * @default false
             */
            llm_cache_enabled: boolean;
            /**
             * Prefetch Enabled
             * @default false
             */
            prefetch_enabled: boolean;
            /**
             * Prefetch Images Enabled
             * @default false
             */
            prefetch_images_enabled: boolean;
            /**
             * Recap Interval
             * @default 3
             */
            recap_interval: number;
            /**
             * Resume Recap Enabled
             * @default true
             */
            resume_recap_enabled: boolean;
            /**
             * Text Provider
             * @default {}
             */
            text_provider: {
                [key: string]: unknown;
            };
            /**
             * Tts Prefs
             * @default {}
             */
            tts_prefs: {
                [key: string]: unknown;
            };
            /**
             * Wizard Defaults
             * @default {}
             */
            wizard_defaults: {
                [key: string]: unknown;
            };
        };
        /**
         * SettingsUpdateRequest
         * @description Partial update for `PUT /api/settings` — only set fields are applied.
         */
        SettingsUpdateRequest: {
            /** Art Enabled */
            art_enabled?: boolean | null;
            /** Auto Open Art Enabled */
            auto_open_art_enabled?: boolean | null;
            /** Auto Recap Enabled */
            auto_recap_enabled?: boolean | null;
            /** Auto Select Enabled */
            auto_select_enabled?: boolean | null;
            /** Character Image Provider */
            character_image_provider?: {
                [key: string]: unknown;
            } | null;
            /** Graphics Mode */
            graphics_mode?: string | null;
            /** Image Provider */
            image_provider?: {
                [key: string]: unknown;
            } | null;
            /** Image Streaming Enabled */
            image_streaming_enabled?: boolean | null;
            /** Llm Cache Enabled */
            llm_cache_enabled?: boolean | null;
            /** Prefetch Enabled */
            prefetch_enabled?: boolean | null;
            /** Prefetch Images Enabled */
            prefetch_images_enabled?: boolean | null;
            /** Recap Interval */
            recap_interval?: number | null;
            /** Resume Recap Enabled */
            resume_recap_enabled?: boolean | null;
            /** Text Provider */
            text_provider?: {
                [key: string]: unknown;
            } | null;
            /** Tts Prefs */
            tts_prefs?: {
                [key: string]: unknown;
            } | null;
            /** Wizard Defaults */
            wizard_defaults?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * StoryImportRequest
         * @description Body for importing characters from another save into the library.
         */
        StoryImportRequest: {
            /**
             * Character Ids
             * @description Character ids to import.
             */
            character_ids: string[];
            /**
             * Save Id
             * @description Source save to pull characters from.
             */
            save_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WizardCharactersRequest
         * @description Body for the character-generation wizard step.
         */
        WizardCharactersRequest: {
            /**
             * Imported Characters
             * @default []
             */
            imported_characters: {
                [key: string]: unknown;
            }[];
            /**
             * Prompt
             * @default
             */
            prompt: string;
            /**
             * Theme
             * @description Theme blob from the theme step.
             */
            theme: {
                [key: string]: unknown;
            };
        };
        /**
         * WizardCharactersResponse
         * @description Generated cast roster.
         */
        WizardCharactersResponse: {
            /** Characters */
            characters: {
                [key: string]: unknown;
            }[];
        };
        /**
         * WizardConfirmRequest
         * @description Body for the confirm-and-create-game wizard step.
         */
        WizardConfirmRequest: {
            /**
             * Art Style
             * @default children's story book
             */
            art_style: string;
            /**
             * Character Prompt
             * @default
             */
            character_prompt: string;
            /** Characters */
            characters: {
                [key: string]: unknown;
            }[];
            /**
             * Narration Style
             * @default third_person
             */
            narration_style: string;
            /**
             * Pacing
             * @default moderate
             */
            pacing: string;
            /**
             * Reader Level
             * @default ages_11_15
             */
            reader_level: string;
            /**
             * Target Major Beats
             * @default 5
             */
            target_major_beats: number;
            /** Theme */
            theme: {
                [key: string]: unknown;
            };
            /**
             * Theme Prompt
             * @default
             */
            theme_prompt: string;
            /** Tone */
            tone: {
                [key: string]: unknown;
            };
        };
        /**
         * WizardConfirmResponse
         * @description Ids of the newly created game.
         */
        WizardConfirmResponse: {
            /**
             * Game Id
             * @description UUID of the new save.
             */
            game_id: string;
            /**
             * Title
             * @description Generated story title.
             */
            title: string;
        };
        /**
         * WizardThemeRequest
         * @description Body for the theme-generation wizard step.
         */
        WizardThemeRequest: {
            /**
             * Prompt
             * @description Free-text premise the theme is derived from.
             */
            prompt: string;
        };
        /**
         * WizardThemeResponse
         * @description Generated theme blob.
         */
        WizardThemeResponse: {
            /** Theme */
            theme: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_characters_api_characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterLibraryResponse"];
                };
            };
        };
    };
    export_character_api_characters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterLibraryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_character_api_characters_create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterLibraryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_from_story_api_characters_import_from_story_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterLibraryEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_character_api_characters__library_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterLibraryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_character_api_characters__library_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterLibraryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_character_api_characters__library_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_portrait_api_characters__library_id__edit_portrait_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortraitEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterLibraryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_character_portrait_api_characters__library_id__portrait_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reference_image_api_characters__library_id__reference_image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_reference_image_api_characters__library_id__reference_image_post: {
        parameters: {
            query?: {
                mode?: string;
            };
            header?: never;
            path: {
                library_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_reference_image_api_characters__library_id__reference_image_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterLibraryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_reference_image_api_characters__library_id__reference_image_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterLibraryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_portrait_api_characters__library_id__regenerate_portrait_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                library_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortraitRegenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterLibraryEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_api_games_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameListResponse"];
                };
            };
        };
    };
    get_game_api_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_game_endpoint_api_games__game_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    advance_game_api_games__game_id__advance_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdvanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_endings_api_games__game_id__endings_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_book_endpoint_api_games__game_id__export_book_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_book_api_games__game_id__export_book_download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_graph_api_games__game_id__graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    jump_to_node_api_games__game_id__jump_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JumpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_path_api_games__game_id__path_get: {
        parameters: {
            query: {
                target_node_id: string;
            };
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeDetail"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prune_subtree_endpoint_api_games__game_id__prune_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PruneRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_node_api_games__game_id__regenerate_node_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateNodeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvanceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    _health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    regenerate_cover_api_images__game_id__cover_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_portrait_image_api_images__game_id__portrait__char_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                char_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_portrait_api_images__game_id__portrait__char_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                char_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortraitEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_outfit_api_images__game_id__portrait__char_id__outfit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                char_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutfitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_outfit_api_images__game_id__portrait__char_id__outfit_revert_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                char_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_outfit_api_images__game_id__portrait__char_id__outfit__outfit_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                char_id: string;
                outfit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_outfit_api_images__game_id__portrait__char_id__outfit__outfit_id__set_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                char_id: string;
                outfit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_portrait_api_images__game_id__portrait__char_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                char_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scene_image_api_images__game_id__scene__node_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_scene_api_images__game_id__scene__node_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SceneEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_scene_api_images__game_id__scene__node_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets_api_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tts_audio_api_tts__game_id___node_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_tts_api_tts__game_id___node_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tts_status_api_tts__game_id___node_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                node_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wizard_characters_api_wizard_characters_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WizardCharactersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WizardCharactersResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wizard_confirm_api_wizard_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WizardConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WizardConfirmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    wizard_theme_api_wizard_theme_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WizardThemeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WizardThemeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
